.TH MYSTRCMP 3 "September 2026" "Version 0.3.1" "MyUtils Library Manual"
.SH NAME
mystrcmp \- compare two strings
.SH SYNOPSIS
.B #include <mystrfunctions.h>
.sp
.BI "int mystrcmp(const char *" s1 ", const char *" s2 ");"
.SH DESCRIPTION
The
.B mystrcmp()
function compares the two strings
.I s1
and
.I s2
character by character.
.SH RETURN VALUE
Returns an integer less than, equal to, or greater than zero if
.I s1
is found, respectively, to be less than, to match, or be greater than
.I s2
.
.SH AUTHOR
Hamza Rehman <bsdsf24m005@pucit.edu.pk>